name: (PREVIEW) Automated deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: 
  push:
    branches: 
      - main

jobs:
  web-deploy:
    name: Deploy portfolio preview
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install NPM Modules
        run: yarn install

      - name: Run Angular tests
        run: yarn test:prod

      - name: Vercel pull
        run: yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel build
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Vercel deploy
        run: yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
