name: (PROD) Deploy portfolio

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: workflow_dispatch

jobs:
  web-deploy:
    name: Deploy portfolio to production
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install NPM Modules
        run: yarn install

      - name: Vercel pull
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Vercel build
        run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Vercel deploy
        run: yarn vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
