name: Run tests on main branch push

on: 
  push:
    branches: 
      - main
      
jobs:
  web-deploy:
    name: Run Angular tests
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use yarn
      uses: borales/actions-yarn@v2.3.0
      
    - name: Install NPM Modules
      run: yarn install

    - name: Run Angular tests
      run: yarn test:prod